export const DEFAULT_MIDDLEWARE_TIMEOUT = 30_000;
export const DEFAULT_PROBABILITY = 0.1;
export const DEFAULT_RETRY_AFTER = 60;
export const DEFAULT_REMAINING_TOKENS = 100;
export const DEFAULT_MAX_TOKENS = 4096;
export const DEFAULT_STALENESS_SECONDS = 3600;
export const MAX_CALL_HISTORY = 1000;
